// Code generated by mockery v1.0.0. DO NOT EDIT.

package sync

import (
	context "context"
	http "net/http"

	messages "github.com/hyperledger-labs/firefly-fabconnect/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// SyncDispatcher is an autogenerated mock type for the SyncDispatcher type
type SyncDispatcher struct {
	mock.Mock
}

// DispatchMsgSync provides a mock function with given fields: ctx, res, req, msg
func (_m *SyncDispatcher) DispatchMsgSync(ctx context.Context, res http.ResponseWriter, req *http.Request, msg *messages.SendTransaction) {
	_m.Called(ctx, res, req, msg)
}
