// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocktx

import (
	client "github.com/hyperledger/firefly-fabconnect/internal/fabric/client"
	mock "github.com/stretchr/testify/mock"

	tx "github.com/hyperledger/firefly-fabconnect/internal/tx"
)

// TxProcessor is an autogenerated mock type for the TxProcessor type
type TxProcessor struct {
	mock.Mock
}

// GetRPCClient provides a mock function with given fields:
func (_m *TxProcessor) GetRPCClient() client.RPCClient {
	ret := _m.Called()

	var r0 client.RPCClient
	if rf, ok := ret.Get(0).(func() client.RPCClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.RPCClient)
		}
	}

	return r0
}

// Init provides a mock function with given fields: _a0
func (_m *TxProcessor) Init(_a0 client.RPCClient) {
	_m.Called(_a0)
}

// OnMessage provides a mock function with given fields: _a0
func (_m *TxProcessor) OnMessage(_a0 tx.TxContext) {
	_m.Called(_a0)
}
