// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockfabricdep

import (
	api "github.com/hyperledger/fabric-sdk-go/pkg/msp/api"

	mock "github.com/stretchr/testify/mock"
)

// CAClient is an autogenerated mock type for the CAClient type
type CAClient struct {
	mock.Mock
}

// Enroll provides a mock function with given fields: _a0
func (_m *CAClient) Enroll(_a0 *api.EnrollmentRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*api.EnrollmentRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllIdentities provides a mock function with given fields: _a0
func (_m *CAClient) GetAllIdentities(_a0 string) ([]*api.IdentityResponse, error) {
	ret := _m.Called(_a0)

	var r0 []*api.IdentityResponse
	if rf, ok := ret.Get(0).(func(string) []*api.IdentityResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.IdentityResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCAInfo provides a mock function with given fields:
func (_m *CAClient) GetCAInfo() (*api.GetCAInfoResponse, error) {
	ret := _m.Called()

	var r0 *api.GetCAInfoResponse
	if rf, ok := ret.Get(0).(func() *api.GetCAInfoResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.GetCAInfoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIdentity provides a mock function with given fields: _a0, _a1
func (_m *CAClient) GetIdentity(_a0 string, _a1 string) (*api.IdentityResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *api.IdentityResponse
	if rf, ok := ret.Get(0).(func(string, string) *api.IdentityResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.IdentityResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ModifyIdentity provides a mock function with given fields: _a0
func (_m *CAClient) ModifyIdentity(_a0 *api.IdentityRequest) (*api.IdentityResponse, error) {
	ret := _m.Called(_a0)

	var r0 *api.IdentityResponse
	if rf, ok := ret.Get(0).(func(*api.IdentityRequest) *api.IdentityResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.IdentityResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*api.IdentityRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reenroll provides a mock function with given fields: _a0
func (_m *CAClient) Reenroll(_a0 *api.ReenrollmentRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*api.ReenrollmentRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Register provides a mock function with given fields: _a0
func (_m *CAClient) Register(_a0 *api.RegistrationRequest) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(*api.RegistrationRequest) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*api.RegistrationRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Revoke provides a mock function with given fields: _a0
func (_m *CAClient) Revoke(_a0 *api.RevocationRequest) (*api.RevocationResponse, error) {
	ret := _m.Called(_a0)

	var r0 *api.RevocationResponse
	if rf, ok := ret.Get(0).(func(*api.RevocationRequest) *api.RevocationResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.RevocationResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*api.RevocationRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
