// Code generated by mockery v1.0.0. DO NOT EDIT.

package async

import (
	context "context"
	http "net/http"

	httprouter "github.com/julienschmidt/httprouter"

	messages "github.com/hyperledger-labs/firefly-fabconnect/internal/messages"

	mock "github.com/stretchr/testify/mock"
)

// AsyncDispatcher is an autogenerated mock type for the AsyncDispatcher type
type AsyncDispatcher struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *AsyncDispatcher) Close() {
	_m.Called()
}

// DispatchMsgAsync provides a mock function with given fields: ctx, msg, ack
func (_m *AsyncDispatcher) DispatchMsgAsync(ctx context.Context, msg map[string]interface{}, ack bool) (*messages.AsyncSentMsg, error) {
	ret := _m.Called(ctx, msg, ack)

	var r0 *messages.AsyncSentMsg
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}, bool) *messages.AsyncSentMsg); ok {
		r0 = rf(ctx, msg, ack)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messages.AsyncSentMsg)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}, bool) error); ok {
		r1 = rf(ctx, msg, ack)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleReceipts provides a mock function with given fields: res, req, params
func (_m *AsyncDispatcher) HandleReceipts(res http.ResponseWriter, req *http.Request, params httprouter.Params) {
	_m.Called(res, req, params)
}

// IsInitialized provides a mock function with given fields:
func (_m *AsyncDispatcher) IsInitialized() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Run provides a mock function with given fields:
func (_m *AsyncDispatcher) Run() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateConf provides a mock function with given fields:
func (_m *AsyncDispatcher) ValidateConf() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
