// Code generated by mockery v1.0.0. DO NOT EDIT.

package receipt

import (
	http "net/http"

	httprouter "github.com/julienschmidt/httprouter"
	mock "github.com/stretchr/testify/mock"
)

// ReceiptStore is an autogenerated mock type for the ReceiptStore type
type ReceiptStore struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *ReceiptStore) Close() {
	_m.Called()
}

// GetReceipt provides a mock function with given fields: res, req, params
func (_m *ReceiptStore) GetReceipt(res http.ResponseWriter, req *http.Request, params httprouter.Params) {
	_m.Called(res, req, params)
}

// GetReceipts provides a mock function with given fields: res, req, params
func (_m *ReceiptStore) GetReceipts(res http.ResponseWriter, req *http.Request, params httprouter.Params) {
	_m.Called(res, req, params)
}

// ProcessReceipt provides a mock function with given fields: msgBytes
func (_m *ReceiptStore) ProcessReceipt(msgBytes []byte) {
	_m.Called(msgBytes)
}
